const express = require('express');
const router = express.Router();
const getController = require('../controller/getController');
const postController =require('../controller/postController');
const userController = require('../controller/userController');
const plansController   = require('../controller/planController');
const revenueController =require('../controller/revenueController');
const couponsController =require('../controller/couponsController');
const transactionController = require('../controller/transactionController');
const feedbackController = require('../controller/feedbackController');
const adminController = require('../controller/adminLoginController');


router.get('/assignments', getController.getAllAssignments);
router.get('/planMaster', getController.getAllplans);
router.get('/lead', getController.getAllLeads);
router.get('/userplan', getController.getAllUserPlan);
router.post('/assignments', postController.createAssignment);
router.post('/leads', postController.createLead);
router.get('/user_details',userController.getUserDashboardData);
router.get('/plan', plansController.getAllPlans);
router.get('/dashboard-stats', plansController.getAnalytics);
router.get('/user-stats', userController.getUserStats);
router.get('/revenue/monthly', revenueController.getMonthlyPlanRevenue);
router.get('/revenue/yearly', revenueController.getYearlyPlanRevenue);
router.get('/revenue/country', revenueController.getRevenueByCountry);
router.get('/revenue/plan', revenueController.getRevenueByPlan);
router.get('/transactions/:userId', userController.getUserTransactions);
router.get('/revenue/platform', revenueController.getRevenueByPlatform);
router.get('/test', (req, res) => {  res.send('✅ API route is working');});
router.get('/coupons', couponsController.getAllCoupons);
router.post('/coupons', couponsController.createCoupon);
router.put('/coupons/:id', couponsController.updateCoupon);
router.delete('/coupons/:id', couponsController.deleteCoupon);
router.get('/coupons/stats', couponsController.getCouponStats);
router.put('/user_details/:id', userController.updateUserFromDashboard);   
router.delete('/user_details/:id', userController.softDeleteUser); 
router.put('/plan/:id', plansController.updatePlan);
router.delete('/plan/:id', plansController.deletePlan);
router.post('/plan',plansController.addPlan);
router.get('transactions/:id', transactionController.getUserWithTransactions);
router.get('/transactions',transactionController.getTransactionHistory);
router.get('/feedback', feedbackController.getAllFeedback);
router.get('/feedback/:userId', feedbackController.getFeedbackByUserId);
router.get('/user/:userId', transactionController.getTransactionsByUserId);
router.get('/leadscount', plansController.getTotalLeads);
router.get('/new-users', userController.getNewUsersWithDetails);
router.post('/admin/login', adminController.loginAdmin);
// router.get('/admin/check', adminController.checkAdminAuth); //
router.get('/revenue/month-year',revenueController.getProfessionalPlanRevenueByMonthYear);
router.get('/stats-count', getController.getStatsCount);
router.get('/users-with-transactions', userController.getUsersWithTransactions);
module.exports = router;
